import type { NextPage } from 'next';
import Head from 'next/head';
import { gql, GraphQLClient } from 'graphql-request';
import { Key, useEffect, useState } from 'react';
import NavBar from '../src/components/NavBar/NavBar';
import Hero from '../src/components/Hero/Hero';
import EventList from '../src/components/EventList/EventList';

export const getStaticProps = async () => {
  const url = process.env.ENDPOINT;

  /* @ts-ignore */

  const graphQLClient = new GraphQLClient(url, {
    headers: {
      Authorization: process.env.GRAPH_CMS_TOKEN,
    },
  });

  const query = gql`
    query {
      events {
        id
        title
        slug
        artists
        description
        price
        date
        thumbnail {
          url
        }
        categories {
          categoryName
        }
      }
    }
  `;

  const data = await graphQLClient.request(query);
  const events = data.events;

  return {
    props: { events },
  };
};

const Home: NextPage = (events) => {
  const [eventsPerPageNumber, setEventsPerPageNumber] = useState(1);

  const loadMoreEvents = () => {
    setEventsPerPageNumber(eventsPerPageNumber + 1);
  };

  return (
    <div>
      <Head>
        <title>EventApp</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <NavBar />
      <Hero />
      {/* @ts-ignore */}
      <EventList events={events} />
      {/* @ts-ignore */}
      {/* {events.events
        .map((item: { thumbnail: { url: string }; id: Key; title: string }) => (
          <div key={item.id}>
            <p>{item.title}</p>
            <img src={item.thumbnail.url} alt='event image' />
          </div>
        ))
        .slice(0, eventsPerPageNumber)}
      <button onClick={loadMoreEvents}>load more</button> */}
    </div>
  );
};

export default Home;
